IMPORT FROM CSV FILE '/tmp/sampledata/CUSTOMER.csv' INTO "CUSTOMER"
  WITH RECORD DELIMITED BY '\n'
  FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/tmp/sampledata/LINEITEM.csv' INTO "LINEITEM"
  WITH RECORD DELIMITED BY '\n'
  FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/tmp/sampledata/NATION.csv' INTO "NATION"
  WITH RECORD DELIMITED BY '\n'
  FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/tmp/sampledata/ORDERS.csv' INTO "ORDERS"
  WITH RECORD DELIMITED BY '\n'
  FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/tmp/sampledata/PART.csv' INTO "PART"
  WITH RECORD DELIMITED BY '\n'
  FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/tmp/sampledata/PARTSUPP.csv' INTO "PARTSUPP"
  WITH RECORD DELIMITED BY '\n'
  FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/tmp/sampledata/REGION.csv' INTO "REGION"
  WITH RECORD DELIMITED BY '\n'
  FIELD DELIMITED BY ',';
IMPORT FROM CSV FILE '/tmp/sampledata/SUPPLIER.csv' INTO "SUPPLIER"
  WITH RECORD DELIMITED BY '\n'
  FIELD DELIMITED BY ',';
